runs:
  using: composite
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: temurin
        java-version: 21
        check-latest: true

    - shell: bash
      run: java --version

    - shell: bash
      run: mvn --version
