runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
        check-latest: true

    - shell: bash
      run: java --version

    - shell: bash
      run: mvn --version
